# Form implementation generated from reading ui file 'Text_To_Speak_Offline.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon
from win32com.client import Dispatch

class Ui_MainWindow(object):
    def speak1(self,str):
        speak = Dispatch("SAPI.spVoice")
        speak.Speak(str)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Speak!")
        MainWindow.setWindowTitle("Speak!")
        MainWindow.setWindowIcon(QIcon("assets/logo.ico"))
        MainWindow.resize(808, 596)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(parent=self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("Assets/backgorund.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.inputbox = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputbox.setGeometry(QtCore.QRect(360, 170, 251, 31))
        self.inputbox.setStyleSheet("QLineEdit#inputbox {\n"
"                width: 100%;\n"
"                font-size: 1.3rem;\n"
"                color: #fff;\n"
"                padding: 7px 0;\n"
"                background: transparent;\n"
"                border: 0;\n"
"                border-bottom: 2px solid #9b9b9b;\n"
"                outline: 0;\n"
"            }\n"
"            QLineEdit#inputbox:focus {\n"
"                border-width: 3px;\n"
"                border-image: linear-gradient(to right, #11998e, #38ef7d);\n"
"                border-image-slice: 1;\n"
"                font-weight: 700;\n"
"                color: #11998e;\n"
"            }")
        self.inputbox.setObjectName("inputbox")
        self.speak = QtWidgets.QPushButton(parent=self.centralwidget)
        self.speak.setGeometry(QtCore.QRect(422, 240, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.speak.setFont(font)
        self.speak.setStyleSheet("QPushButton#speak {\n"
"                padding: 2px 30px;\n"
"                font-size: 1.5rem;\n"
"                color: #11998e;\n"
"                background-color: transparent;\n"
"                border: 2px solid rgba(0, 0, 0, 0.5);\n"
"                border-radius: 4px;\n"
"                text-transform: uppercase;\n"
"                letter-spacing: 0.1rem;\n"
"                position: relative;\n"
"                z-index: 1;\n"
"                transition: 0.5s;\n"
"            }\n"
"            QPushButton#speak:hover {\n"
"                color: #fff;\n"
"            }\n"
"            QPushButton#speak::before {\n"
"                content: \'\';\n"
"                position: absolute;\n"
"                top: 0;\n"
"                left: 0;\n"
"                width: 100%;\n"
"                height: 100%;\n"
"                background: #11998e;\n"
"                z-index: -1;\n"
"                transform: scale(0);\n"
"                transition: 0.5s;\n"
"            }\n"
"            QPushButton#speak:hover::before {\n"
"                transform: scale(1);\n"
"                transition-delay: 0.5s;\n"
"                box-shadow: 0 0 10px #11998e, 0 0 30px #11998e, 0 0 60px #11998e;\n"
"            }\n"
"            QPushButton#speak span {\n"
"                position: absolute;\n"
"                background: #11998e;\n"
"                border-radius: 2px;\n"
"                box-shadow: 0 0 10px #11998e, 0 0 20px #11998e, 0 0 30px #11998e, 0 0 50px #11998e, 0 0 100px #11998e;\n"
"                transition: 0.5s ease-in-out;\n"
"                transition-delay: 0.25s;\n"
"                pointer-events: none;\n"
"            }\n"
"            QPushButton#speak span:nth-child(1), QPushButton#speak span:nth-child(3) {\n"
"                width: 40px;\n"
"                height: 4px;\n"
"            }\n"
"            QPushButton#speak span:nth-child(2), QPushButton#speak span:nth-child(4) {\n"
"                width: 4px;\n"
"                height: 40px;\n"
"            }\n"
"            QPushButton#speak span:nth-child(1) {\n"
"                top: calc(50% - 2px);\n"
"                left: -50px;\n"
"                transform-origin: left;\n"
"            }\n"
"            QPushButton#speak:hover span:nth-child(1) {\n"
"                left: 50%;\n"
"            }\n"
"            QPushButton#speak span:nth-child(3) {\n"
"                top: calc(50% - 2px);\n"
"                right: -50px;\n"
"                transform-origin: right;\n"
"            }\n"
"            QPushButton#speak:hover span:nth-child(3) {\n"
"                right: 50%;\n"
"            }\n"
"            QPushButton#speak span:nth-child(2) {\n"
"                left: calc(50% - 2px);\n"
"                top: -50px;\n"
"                transform-origin: top;\n"
"            }\n"
"            QPushButton#speak:hover span:nth-child(2) {\n"
"                top: 50%;\n"
"            }\n"
"            QPushButton#speak span:nth-child(4) {\n"
"                left: calc(50% - 2px);\n"
"                bottom: -50px;\n"
"                transform-origin: bottom;\n"
"            }\n"
"            QPushButton#speak:hover span:nth-child(4) {\n"
"                bottom: 50%;\n"
"            }")
        self.speak.setObjectName("speak")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.speak.clicked.connect(lambda: self.speak1(self.inputbox.text()))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputbox.setPlaceholderText(_translate("MainWindow", "                  Enter the Text here"))
        self.speak.setText(_translate("MainWindow", "Speak !"))
        self.speak.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
